name: Build and Upload Dify Plugin

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for uploading to releases
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dify Plugin CLI
        run: |
          pip install git+https://github.com/langgenius/dify-plugin-cli.git@main

      - name: Build plugin
        run: |
          dify-plugin-cli build

      - name: Upload to GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload v1.0.0 dist/*.difypkg --clobber
